export const EXTENSION_ID = 'bookmarks';
export const EXTENSION_VIEW_ID = 'bookmarks';

/** Commands */
export const CMD_TOGGLE_BOOKMARK_WITH_LABEL = 'CMD_TOGGLE_BOOKMARK_WITH_LABEL';
export const CMD_TOGGLE_LINE_BOOKMARK = 'CMD_TOGGLE_LINE_BOOKMARK';
export const CMD_TOGGLE_NORMAL_BOOKMARK = 'CMD_TOGGLE_NORMAL_BOOKMARK';
export const CMD_TOGGLE_LOW_BOOKMARK = 'CMD_TOGGLE_LOW_BOOKMARK';
export const CMD_TOGGLE_HiGH_BOOKMARK = 'CMD_TOGGLE_HiGH_BOOKMARK';
